/**
 * Client-side keyword search over the prebuilt office-hours transcript index.
 *
 * The index is a static JSON artifact generated by
 * scripts/build-office-hours-index.mjs and served from /public, so search runs
 * entirely in the browser after a single fetch — no serverless round-trip. The
 * record shape is backend-agnostic ({ sessionId, ... start, text }), so this
 * keyword matcher can later be swapped for embeddings/vector search without
 * reshaping the data or the result type.
 */

/** One indexed transcript segment (mirrors the build script's record shape). */
export interface OfficeHoursSearchRecord {
  sessionId: string;
  title: string;
  /** ISO date (YYYY-MM-DD) of the session. */
  date: string;
  /** Which half the segment belongs to — drives the gate on click. */
  half: "free" | "gated";
  /** YouTube id for this half's video. */
  youtubeId: string;
  /** Segment start, in seconds, within its half's video. */
  start: number;
  /** Segment transcript text (the searchable body + snippet source). */
  text: string;
}

export interface OfficeHoursSearchIndex {
  version: number;
  strategy: string;
  generatedAt: string;
  records: OfficeHoursSearchRecord[];
}

/** A ranked result: the best-matching segment for a session. */
export interface OfficeHoursSearchResult {
  sessionId: string;
  title: string;
  date: string;
  half: "free" | "gated";
  youtubeId: string;
  startSeconds: number;
  snippet: string;
  score: number;
}

export const SEARCH_INDEX_URL = "/office-hours-search-index.json";

let indexPromise: Promise<OfficeHoursSearchRecord[]> | null = null;

/**
 * Fetch (and cache) the static search index. Client-only — guards SSR/prerender,
 * where there is no `fetch`/`window`, by returning an empty index.
 */
export async function loadOfficeHoursSearchIndex(): Promise<
  OfficeHoursSearchRecord[]
> {
  if (typeof window === "undefined") return [];
  if (!indexPromise) {
    indexPromise = fetch(SEARCH_INDEX_URL)
      .then((r) => (r.ok ? r.json() : { records: [] }))
      .then((data: Partial<OfficeHoursSearchIndex>) => data.records ?? [])
      .catch(() => {
        // Allow a later retry if the first fetch failed (e.g. offline).
        indexPromise = null;
        return [];
      });
  }
  return indexPromise;
}

/** Format seconds as `m:ss` (or `h:mm:ss` past an hour). */
export function formatTimecode(totalSeconds: number): string {
  const s = Math.max(0, Math.floor(totalSeconds));
  const hours = Math.floor(s / 3600);
  const minutes = Math.floor((s % 3600) / 60);
  const seconds = s % 60;
  const pad = (n: number) => n.toString().padStart(2, "0");
  return hours > 0
    ? `${hours}:${pad(minutes)}:${pad(seconds)}`
    : `${minutes}:${pad(seconds)}`;
}

function tokenize(query: string): string[] {
  return query
    .toLowerCase()
    .split(/[^a-z0-9]+/i)
    .filter(Boolean);
}

// Trim a snippet to a window around the first matched term so results stay short.
function buildSnippet(text: string, terms: string[], max = 160): string {
  if (text.length <= max) return text;
  const lower = text.toLowerCase();
  const firstHit = terms
    .map((t) => lower.indexOf(t))
    .filter((i) => i >= 0)
    .sort((a, b) => a - b)[0];
  if (firstHit === undefined) return text.slice(0, max).trimEnd() + "…";
  const start = Math.max(0, firstHit - 40);
  const slice = text.slice(start, start + max).trim();
  return `${start > 0 ? "…" : ""}${slice}${start + max < text.length ? "…" : ""}`;
}

/**
 * Case-insensitive, multi-term keyword search. Every query term must appear in a
 * segment for it to match (AND semantics). Segments are scored by how often the
 * terms occur (with a small bonus for whole-word hits), then collapsed to the
 * single best-scoring segment per session so each session surfaces once at its
 * most relevant moment. Results are returned ranked, most relevant first.
 */
export function searchOfficeHours(
  query: string,
  records: OfficeHoursSearchRecord[],
): OfficeHoursSearchResult[] {
  const terms = tokenize(query);
  if (terms.length === 0) return [];

  const bestBySession = new Map<string, OfficeHoursSearchResult>();

  for (const record of records) {
    const haystack = record.text.toLowerCase();

    let score = 0;
    let matchedAll = true;
    for (const term of terms) {
      const occurrences = haystack.split(term).length - 1;
      if (occurrences === 0) {
        matchedAll = false;
        break;
      }
      score += occurrences;
      // Reward whole-word matches over substring hits (e.g. "skill" in "skills").
      if (new RegExp(`\\b${term}\\b`).test(haystack)) score += 1;
    }
    if (!matchedAll) continue;

    const existing = bestBySession.get(record.sessionId);
    if (!existing || score > existing.score) {
      bestBySession.set(record.sessionId, {
        sessionId: record.sessionId,
        title: record.title,
        date: record.date,
        half: record.half,
        youtubeId: record.youtubeId,
        startSeconds: record.start,
        snippet: buildSnippet(record.text, terms),
        score,
      });
    }
  }

  return [...bestBySession.values()].sort((a, b) => {
    if (b.score !== a.score) return b.score - a.score;
    return b.date.localeCompare(a.date);
  });
}
