/**
 * Client-side keyword search over the prebuilt office-hours transcript index.
 *
 * The index is a static JSON artifact generated by
 * scripts/build-office-hours-index.mjs from the REAL Airtable + Google-Doc
 * transcripts, and served from /public — so search runs entirely in the browser
 * after a single fetch, no serverless round-trip. Each index entry is one
 * session with ~5-minute segments ({ text, startSeconds }); we flatten those to
 * per-segment records here. The record shape is backend-agnostic, so this keyword
 * matcher can later be swapped for embeddings/vector search without reshaping the
 * data or the result type.
 */

/** One session entry as stored in the static index. */
export interface OfficeHoursIndexSession {
  sessionId: string;
  title: string;
  /** ISO date (YYYY-MM-DD) of the session. */
  date: string;
  /** YouTube id of the real recording (both halves are the same upload). */
  youtubeId: string;
  /** Total recording length in seconds (drives the free/gated split). */
  durationSeconds: number;
  segments: { text: string; startSeconds: number }[];
}

export interface OfficeHoursSearchIndex {
  version: number;
  strategy: string;
  generatedAt: string;
  sessions: OfficeHoursIndexSession[];
}

/** One flattened, searchable transcript segment. */
export interface OfficeHoursSearchRecord {
  sessionId: string;
  title: string;
  date: string;
  youtubeId: string;
  /** Segment start, in seconds, within the recording. */
  startSeconds: number;
  /**
   * Members-only? Each real recording is one video, so — mirroring 001's
   * free-first-half / gated-second-half model — segments in the SECOND half of
   * the recording are gated and route through the signup gate on click.
   */
  gated: boolean;
  /** Scrubbed segment text (the searchable body + snippet source). */
  text: string;
}

/** A ranked result: the best-matching segment for a session. */
export interface OfficeHoursSearchResult {
  sessionId: string;
  title: string;
  date: string;
  youtubeId: string;
  startSeconds: number;
  gated: boolean;
  snippet: string;
  score: number;
}

export const SEARCH_INDEX_URL = "/office-hours-search-index.json";

let indexPromise: Promise<OfficeHoursSearchRecord[]> | null = null;

/** Flatten the per-session index into per-segment search records. */
function flattenIndex(
  sessions: OfficeHoursIndexSession[],
): OfficeHoursSearchRecord[] {
  const records: OfficeHoursSearchRecord[] = [];
  for (const session of sessions ?? []) {
    // Midpoint of the recording; segments at/after it are the gated second half.
    const midpoint =
      session.durationSeconds > 0 ? session.durationSeconds / 2 : Infinity;
    for (const seg of session.segments ?? []) {
      const text = (seg.text ?? "").trim();
      if (!text) continue;
      records.push({
        sessionId: session.sessionId,
        title: session.title,
        date: session.date,
        youtubeId: session.youtubeId,
        startSeconds: Math.max(0, Math.floor(seg.startSeconds ?? 0)),
        gated: (seg.startSeconds ?? 0) >= midpoint,
        text,
      });
    }
  }
  return records;
}

/**
 * Fetch (and cache) the static search index. Client-only — guards SSR/prerender,
 * where there is no `fetch`/`window`, by returning an empty index.
 */
export async function loadOfficeHoursSearchIndex(): Promise<
  OfficeHoursSearchRecord[]
> {
  if (typeof window === "undefined") return [];
  if (!indexPromise) {
    indexPromise = fetch(SEARCH_INDEX_URL)
      .then((r) => (r.ok ? r.json() : { sessions: [] }))
      .then((data: Partial<OfficeHoursSearchIndex>) =>
        flattenIndex(data.sessions ?? []),
      )
      .catch(() => {
        // Allow a later retry if the first fetch failed (e.g. offline).
        indexPromise = null;
        return [];
      });
  }
  return indexPromise;
}

/** Format seconds as `m:ss` (or `h:mm:ss` past an hour). */
export function formatTimecode(totalSeconds: number): string {
  const s = Math.max(0, Math.floor(totalSeconds));
  const hours = Math.floor(s / 3600);
  const minutes = Math.floor((s % 3600) / 60);
  const seconds = s % 60;
  const pad = (n: number) => n.toString().padStart(2, "0");
  return hours > 0
    ? `${hours}:${pad(minutes)}:${pad(seconds)}`
    : `${minutes}:${pad(seconds)}`;
}

function tokenize(query: string): string[] {
  return query
    .toLowerCase()
    .split(/[^a-z0-9]+/i)
    .filter(Boolean);
}

// Trim a snippet to a window around the first matched term so results stay short.
function buildSnippet(text: string, terms: string[], max = 160): string {
  if (text.length <= max) return text;
  const lower = text.toLowerCase();
  const firstHit = terms
    .map((t) => lower.indexOf(t))
    .filter((i) => i >= 0)
    .sort((a, b) => a - b)[0];
  if (firstHit === undefined) return text.slice(0, max).trimEnd() + "…";
  const start = Math.max(0, firstHit - 40);
  const slice = text.slice(start, start + max).trim();
  return `${start > 0 ? "…" : ""}${slice}${start + max < text.length ? "…" : ""}`;
}

/**
 * Case-insensitive, multi-term keyword search. Every query term must appear in a
 * segment for it to match (AND semantics). Segments are scored by how often the
 * terms occur (with a small bonus for whole-word hits), then collapsed to the
 * single best-scoring segment per session so each session surfaces once at its
 * most relevant moment. Results are returned ranked, most relevant first.
 */
export function searchOfficeHours(
  query: string,
  records: OfficeHoursSearchRecord[],
): OfficeHoursSearchResult[] {
  const terms = tokenize(query);
  if (terms.length === 0) return [];

  const bestBySession = new Map<string, OfficeHoursSearchResult>();

  for (const record of records) {
    const haystack = record.text.toLowerCase();

    let score = 0;
    let matchedAll = true;
    for (const term of terms) {
      const occurrences = haystack.split(term).length - 1;
      if (occurrences === 0) {
        matchedAll = false;
        break;
      }
      score += occurrences;
      // Reward whole-word matches over substring hits (e.g. "skill" in "skills").
      if (new RegExp(`\\b${term}\\b`).test(haystack)) score += 1;
    }
    if (!matchedAll) continue;

    const existing = bestBySession.get(record.sessionId);
    if (!existing || score > existing.score) {
      bestBySession.set(record.sessionId, {
        sessionId: record.sessionId,
        title: record.title,
        date: record.date,
        youtubeId: record.youtubeId,
        startSeconds: record.startSeconds,
        gated: record.gated,
        snippet: buildSnippet(record.text, terms),
        score,
      });
    }
  }

  return [...bestBySession.values()].sort((a, b) => {
    if (b.score !== a.score) return b.score - a.score;
    return b.date.localeCompare(a.date);
  });
}
